development:
  adapter:  mysql
  host:     127.0.0.1
  username: root
  password: 1234
  database: ttc-ticketeer
  pool:     5
  timeout:  5000

#production:
#  adapter: mysql
#  encoding: utf8
#  reconnect: false
#  database: somedatabase_dev
#  pool: 5
#  username: root
#  password:
#  socket: /var/run/mysqld/mysqld.sock
#
#test: &test
#  adapter: sqlite3
#  database: db/test.sqlite3
#  pool: 5
#  timeout: 5000